### ISSUE TITLE
Make the code public

### ISSUE THREAD

**Issue by JannoTjarks** [punk7890/Star-Fox-64-Randomizer#2]
Hi @punk7890,

i wanted a STARFOX 64 randomizer since years and I already tried it by my own an failed most the time. Thank you very much for your work! 

Would it be possible to share your code with us so we can contribute to it and find an understanding about the logic in the background?

Greetings 
Janno

**Comment by punk7890** [comment]
I would like to share and make it public some time, however it's all in raw MIPS assembly which I reckon isn't widely known by people, and the second issue would be many poorly written sections due to oversights / bug fixes. The way I coded things is not easily shiftable like any standard high level programming language. I also use a very old disassembler called "ps2dis" (which isn't for the N64 but works well enough).

I do intended to fix up and optimize code when everything is finished (I don't know when it will be considered "finished").

The last issue would be its injected into ROM in an unorthodox, non-standard way and would make contributing and making changes difficult. Once optimizing code is done and I do a complete re-layout of things, it should make contributing easier.

Glad you're enjoying it so far.
