### ISSUE TITLE
Hey, I have a question/idea

### ISSUE THREAD

**Issue by agent72** [punk7890/Star-Fox-64-Randomizer#3]
So, to fully contextualize, I was working a gig on an event, I was working in the "games" part of the event, the quotations are bc it was severely lacking in that aspect, it was more of a VR experience and MK11, Fifa and Mario Kart if you wanted to play something, and it also had a ""retro"" option, the 2 quotation marks imply that it was lacking even further, they used a TV Box that couldn't even handle a SNES properly, but anyway, that experience gave me an idea, what if it was actually well made and put the necessary effort, to make a selection of games that can work in small burst sessions of 5min/a match(that depending on each game); And one of those games I thought that could work for that is Star Fox 64, but not base game, my idea was that you had a separate menu to select what stages and stage routes you can get, the player starts the game, and he would play through that stage, he would always start with the base kit, both wings, laser 1, 3 bombs and 1 life, after he finishes the stage the option to play again on an entirely different stage appears, this allows variety to all players in a line, and a small quick burst section of 5 minutes or less; I shared my idea on reddit and they told me to check the randomizer, so my question is, is it possible to use your randomizer like this? And if so can you teach me which options in case I get called to help in another event? Or if it can't do that, would you consider making as a side project a "Star Fox 64 Event Edition" that could be used on gaming events, so the player doesn't only play Corneria again and again and again?

**Comment by punk7890** [comment]
There is a "Choose Planets" option that allows the player to play any level they wish or choose to repeat a level if they want as well. In order to actually finish a run using this option, the planet must be either Area 6 or Bolse for the 5th or less planet.

Outside of "Choose Planets" there is an option to disable entering the same planet again ("Allow Same Planets" set to off) if the randomizer was on so the player would never get a planet that they cleared during that run.
